# Generated by Django 5.2 on 2026-07-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_shipping_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
