# Generated by Django 5.2 on 2026-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_address_options_alter_adminlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Customer'), ('seller', 'Vendor / Seller'), ('admin', 'Administrator')], default='user', max_length=10),
        ),
    ]
